# fly.toml app configuration file
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "goserver-jqi"
primary_region = "iad"

[build]
  # If you have a Dockerfile, specify it here:
  # dockerfile = "Dockerfile"
  
  # Or use Go buildpack (uncomment if no Dockerfile):
  # builder = "paketobuildpacks/builder:base"
  # buildpacks = ["gcr.io/paketo-buildpacks/go"]

[env]
  PORT = "8080"
  GO_ENV = "production"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
  
  [http_service.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20

[[vm]]
  memory = "256mb"
  cpu_kind = "shared"
  cpus = 1

# Health check configuration (optional)
[[http_service.checks]]
  grace_period = "5s"
  interval = "10s"
  method = "GET"
  path = "/"
  protocol = "http"
  timeout = "2s"
